FROM php:7.4-apache

# Install some PHP extensions
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zlib1g-dev

RUN docker-php-ext-install zip


# Expose port 80
EXPOSE 80

#docker run -p 8080:80 -d -v /Users/dan/site:/var/www/site mysite